Deal with do_rsync error returns.

diff --git a/quick-fedora-mirror b/quick-fedora-mirror
--- a/quick-fedora-mirror
+++ b/quick-fedora-mirror
@@ -1429,10 +1429,9 @@ if [[ -n $rsyncdryrun ]]; then
     extra+=(-n)
 fi
 do_rsync $REMOTE/$MASTERMODULE/ $DESTD master-transferlist.sorted extra
-rsyncreturn=$?
-if [[ $rsyncreturn -ne 0 ]]; then
-    (>&2 echo "rsync finished with nonzero exit status.\nWill not check in or delete anything.")
-    logit E skipping further operations due to rsync failure
+if (( ? != 0 )); then
+    (>&2 echo "rsync failed; aborting run.\nWill not check in or delete anything.")
+    logit "E Skipping further operations due to rsync failure."
     finish 1
 fi
 
